<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/python_programs/blob/main/matrix_multiplication_engine.py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
"""
Problem 17: Perform matrix multiplication
"""

import numpy as np

def get_matrix(rows, cols, name):
    """
    Collect matrix input from user
    """
    matrix = []
    print(f"Enter {name} ({rows}x{cols}):")

    for i in range(rows):
        while True:
            try:
                row = list(map(int, input(f"Row {i+1}: ").split()))
                if len(row) != cols:
                    print("Incorrect input.")
                    continue
                matrix.append(row)
                break
            except ValueError:
                print("Invalid input.")

    return np.array(matrix)


# Take both matrices
m1 = get_matrix(3, 4, "Matrix 1")
m2 = get_matrix(4, 3, "Matrix 2")

# Perform matrix multiplication
result = np.matmul(m1, m2)

# Display result
print("\nResult Matrix:\n", result)

Enter Matrix 1 (3x4):
Row 1: 2 3 4 5
Row 2: 2 3 5 6
Row 3: 3 4 5 6
Enter Matrix 2 (4x3):
Row 1: 3 4 5
Row 2: 2 3 6
Row 3: 4 6 7
Row 4: 3 8 9

Result Matrix:
 [[ 43  81 101]
 [ 50  95 117]
 [ 55 102 128]]
